USE SM_db

IF OBJECT_ID('dbo.xxxxBOM', 'U') IS NOT NULL
DROP TABLE dbo.xxxxBOM
GO
-- Create the table in the specified schema
CREATE TABLE dbo.xxxxBOM
(
   [LINE]                  INTEGER PRIMARY KEY 
  ,[QTY]                   INTEGER 
  ,[PROJECT_TAG]           VARCHAR(7)
  ,[DESCRIPTION]           VARCHAR(88)
  ,[MFG_PART_NO]           VARCHAR(18)
  ,[SM_PART_NO]            INTEGER 
  ,[MANUFACTURER]          VARCHAR(7)
  ,[REV_CODE]              VARCHAR(1)
  ,[REV_NUM]               INTEGER
  ,[VENDOR]                VARCHAR(5)
  ,[COST_PER]              NUMERIC(7,2)
  ,[EXT_COST]              NUMERIC(8,2)
  ,[PRICE_PER]             NUMERIC(8,2)
  ,[EXT_PRICE]             NUMERIC(10,2)
  ,[LEADTIME]              VARCHAR(8)
  ,[NOTES]                 VARCHAR(7)
  ,[COMP_WEIGHT]           VARCHAR(5)
  ,[TOTAL_WEIGHT]          VARCHAR(6)
  ,[HAZARDOUS_MARKING]     VARCHAR(27)
  ,[T_CLASS]               VARCHAR(2)
  ,[AMB_TEMP_MIN]          VARCHAR(6)
  ,[AMB_TEMP_MAX]          VARCHAR(5)
  ,[OPERATING_TEMP_MIN]    VARCHAR(6)
  ,[OPERATING_TEMP_MAX]    VARCHAR(5)
  ,[MAX_THERMAL_DISSIPATION] VARCHAR(22)
  ,[ATEX_CERTIFICATE]      VARCHAR(24)
  ,[IECEx_CERTIFICATE]     VARCHAR(18)
  ,[EAC_CERTIFICATE]       VARCHAR(30)
);
INSERT INTO dbo.xxxxBOM([LINE],[QTY],[PROJECT_TAG],[DESCRIPTION],[MFG_PART_NO],[SM_PART_NO],[MANUFACTURER],[REV_CODE],[REV_NUM],[VENDOR],[COST_PER],[EXT_COST],[PRICE_PER],[EXT_PRICE],[LEADTIME],[NOTES],[COMP_WEIGHT],[TOTAL_WEIGHT],[HAZARDOUS_MARKING],[T_CLASS],[AMB_TEMP_MIN],[AMB_TEMP_MAX],[OPERATING_TEMP_MIN],[OPERATING_TEMP_MAX],[MAX_THERMAL_DISSIPATION],[ATEX_CERTIFICATE],[IECEx_CERTIFICATE],[EAC_CERTIFICATE]) VALUES (1,8,'2656sdf','TB30','6SL3055-0AA00-2TA0',520262,'Siemens','P',1,'Exloc',681.12,5449.00,60262.00,100000.00,'14 weeks','bla','22lbs','44lbs','Ex d [ia Ga or ib] IIB','T6','''-20?C','+55?C','''-20?C','+55?C','8.34 BTU/hrr',NULL,'IECEx INE 10.0015X',NULL);
INSERT INTO dbo.xxxxBOM([LINE],[QTY],[PROJECT_TAG],[DESCRIPTION],[MFG_PART_NO],[SM_PART_NO],[MANUFACTURER],[REV_CODE],[REV_NUM],[VENDOR],[COST_PER],[EXT_COST],[PRICE_PER],[EXT_PRICE],[LEADTIME],[NOTES],[COMP_WEIGHT],[TOTAL_WEIGHT],[HAZARDOUS_MARKING],[T_CLASS],[AMB_TEMP_MIN],[AMB_TEMP_MAX],[OPERATING_TEMP_MIN],[OPERATING_TEMP_MAX],[MAX_THERMAL_DISSIPATION],[ATEX_CERTIFICATE],[IECEx_CERTIFICATE],[EAC_CERTIFICATE]) VALUES (2,8,'ASdf6','Basic Operator Panel','6SL3055-0AA00-4BA0',651651,'Siemens','P',5,'Abb',68.51,548.10,60548.00,200000.00,'1 weeks','bla','23lbs','55lbs','II 3 G    Ex nA IIC T4 Gc','T4','''-20?C','+55?C','''-20?C','+55?C','10.32 BTU/hr','DEMKO 04 ATEX 0330347X',NULL,NULL);
INSERT INTO dbo.xxxxBOM([LINE],[QTY],[PROJECT_TAG],[DESCRIPTION],[MFG_PART_NO],[SM_PART_NO],[MANUFACTURER],[REV_CODE],[REV_NUM],[VENDOR],[COST_PER],[EXT_COST],[PRICE_PER],[EXT_PRICE],[LEADTIME],[NOTES],[COMP_WEIGHT],[TOTAL_WEIGHT],[HAZARDOUS_MARKING],[T_CLASS],[AMB_TEMP_MIN],[AMB_TEMP_MAX],[OPERATING_TEMP_MIN],[OPERATING_TEMP_MAX],[MAX_THERMAL_DISSIPATION],[ATEX_CERTIFICATE],[IECEx_CERTIFICATE],[EAC_CERTIFICATE]) VALUES (3,7,'Er262','DRIVE-CLiQ cable; DRIVE-CLiQ cable (in fixed lengths) IP20/IP20 (fixed mounting); 0.95 m','6SL3060-4AA10-0AA0',5050262,'Siemens','A',2,'Wago',45.44,318.10,1262.00,3000000.00,'34 weeks','blah','25lbs','66lbs','II 3 G    Ex nA IIC T4 Gc','T4','''-20?C','+55?C','''-20?C','+55?C','7.5 BTU/hr','DEMKO 04 ATEX 0330347X',NULL,NULL);
INSERT INTO dbo.xxxxBOM([LINE],[QTY],[PROJECT_TAG],[DESCRIPTION],[MFG_PART_NO],[SM_PART_NO],[MANUFACTURER],[REV_CODE],[REV_NUM],[VENDOR],[COST_PER],[EXT_COST],[PRICE_PER],[EXT_PRICE],[LEADTIME],[NOTES],[COMP_WEIGHT],[TOTAL_WEIGHT],[HAZARDOUS_MARKING],[T_CLASS],[AMB_TEMP_MIN],[AMB_TEMP_MAX],[OPERATING_TEMP_MIN],[OPERATING_TEMP_MAX],[MAX_THERMAL_DISSIPATION],[ATEX_CERTIFICATE],[IECEx_CERTIFICATE],[EAC_CERTIFICATE]) VALUES (4,11,'fds6','DRIVE-CLiQ cable; DRIVE-CLiQ cable (in fixed lengths) IP20/IP20 (fixed mounting); 0.60 m','6SL3060-4AU00-0AA0',165050,'Siemens','P',3,'Exloc',40.81,448.90,1512.00,40000.00,'10 weeks','dfsa','0kg','67lbs','II 3 G    Ex nA IIC T4 Gc','T4','''-40?C','+70?C','''-20?C','+55?C','6.8 BTU/hr @ 28.8V DC','DEMKO 04 ATEX 0330347X',NULL,NULL);
INSERT INTO dbo.xxxxBOM([LINE],[QTY],[PROJECT_TAG],[DESCRIPTION],[MFG_PART_NO],[SM_PART_NO],[MANUFACTURER],[REV_CODE],[REV_NUM],[VENDOR],[COST_PER],[EXT_COST],[PRICE_PER],[EXT_PRICE],[LEADTIME],[NOTES],[COMP_WEIGHT],[TOTAL_WEIGHT],[HAZARDOUS_MARKING],[T_CLASS],[AMB_TEMP_MIN],[AMB_TEMP_MAX],[OPERATING_TEMP_MIN],[OPERATING_TEMP_MAX],[MAX_THERMAL_DISSIPATION],[ATEX_CERTIFICATE],[IECEx_CERTIFICATE],[EAC_CERTIFICATE]) VALUES (5,6,'sfxxxx','SITOP modular 10.00 A','6EP1334-3BA10',502620,'Siemens','P',3,'Abb',360.00,2160.00,12168.00,50505.00,'1 weeks','asdfasd','3kg','88lbs','II 3 G    Ex nA IIC T4 Gc','T4','''-40?C','+70?C','''-20?C','+55?C','6.8 BTU/hr @ 28.8V DC','DEMKO 04 ATEX 0330347X',NULL,NULL);
INSERT INTO dbo.xxxxBOM([LINE],[QTY],[PROJECT_TAG],[DESCRIPTION],[MFG_PART_NO],[SM_PART_NO],[MANUFACTURER],[REV_CODE],[REV_NUM],[VENDOR],[COST_PER],[EXT_COST],[PRICE_PER],[EXT_PRICE],[LEADTIME],[NOTES],[COMP_WEIGHT],[TOTAL_WEIGHT],[HAZARDOUS_MARKING],[T_CLASS],[AMB_TEMP_MIN],[AMB_TEMP_MAX],[OPERATING_TEMP_MIN],[OPERATING_TEMP_MAX],[MAX_THERMAL_DISSIPATION],[ATEX_CERTIFICATE],[IECEx_CERTIFICATE],[EAC_CERTIFICATE]) VALUES (6,6,'656sd','Active Line Module; 80.00 kW','6SL3130-7TE28-0AA3',560650,'Siemens','O',1,'Wago',7577.75,45466.50,16516.00,6050.00,'3 weeks','asdfasd','5kfg','90lbs','II 3 G    Ex nA IIC T4 Gc','T4','''-40?C','+70?C','''-40?C','+70?C','2.0 BTU/hr @ 28.8V DC','DEMKO 04 ATEX 0330347X',NULL,NULL);
INSERT INTO dbo.xxxxBOM([LINE],[QTY],[PROJECT_TAG],[DESCRIPTION],[MFG_PART_NO],[SM_PART_NO],[MANUFACTURER],[REV_CODE],[REV_NUM],[VENDOR],[COST_PER],[EXT_COST],[PRICE_PER],[EXT_PRICE],[LEADTIME],[NOTES],[COMP_WEIGHT],[TOTAL_WEIGHT],[HAZARDOUS_MARKING],[T_CLASS],[AMB_TEMP_MIN],[AMB_TEMP_MAX],[OPERATING_TEMP_MIN],[OPERATING_TEMP_MAX],[MAX_THERMAL_DISSIPATION],[ATEX_CERTIFICATE],[IECEx_CERTIFICATE],[EAC_CERTIFICATE]) VALUES (7,6,'sdf65','Active Interface Module','6SL3100-0BE28-0AB0',650650,'Siemens','O',1,'Wago',4563.66,27382.00,21651.00,5605.00,'2 weeks','asdfd','3sdf','100lbs','II 3 G    Ex nA IIC T4 Gc','T4','''-20?C','+55?C','''-40?C','+70?C','10.0 BTU/hr @ 28.8V DC','DEMKO 04 ATEX 0330347X',NULL,NULL);

