USE SM_db

IF OBJECT_ID('dbo.xxxxBOM', 'U') IS NOT NULL
DROP TABLE dbo.TableName
GO
-- Create the table in the specified schema
CREATE TABLE dbo.xxxxBOM
(
    ID TINYINT NOT NULL PRIMARY KEY, -- primary key column
    QTY TINYINT,
    PROJECT_TAG VARCHAR,
    DESCRIPTION VARCHAR,
    MFG_PART_NO VARCHAR,
    SM_PART_NO VARCHAR,
    MANUFACTURER VARCHAR,
    REV_CODE CHAR(1),
    REV_NUM TINYINT,
    VENDOR VARCHAR,
    COST_PER NUMERIC(15,2),
    EXT_COST NUMERIC(15,2),
    PRICE_PER NUMERIC(15,2),
    EXT_PRICE NUMERIC(15,2),
    LEADTIME VARCHAR,
    NOTES VARCHAR,
    COMP_WEIGHT VARCHAR,
    TOTAL_WEIGHT VARCHAR,
    HAZARDOUS_MARKING VARCHAR,
    T_CLASS VARCHAR,
    AMBIENT_TEMPERATURE VARCHAR,
    OPERATING_TEMP_MAX VARCHAR,
    OPERATING_TEMP_MIN VARCHAR,
    MAX_THERMAL_DISSIPATION VARCHAR,
    ATEX_CERTIFICATE VARCHAR,
    IECEX_CERTIFICATE VARCHAR,
    EAC_CERTIFICATE VARCHAR,





    -- specify more columns here
);
